# Generated by Django 4.1.7 on 2023-03-05 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simple_hamburger', models.IntegerField()),
                ('middle_hamburger', models.IntegerField()),
                ('big_hamburger', models.IntegerField()),
                ('water', models.IntegerField()),
                ('hot_chocolate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='restaurants.menu')),
            ],
        ),
    ]
